import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Layout (auth)",
    description: "Generated by create next app",
  };
  
  export default function LayoutAuth({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`antialiased`}
        >
          {children}
        </body>
      </html>
    );
  }
  