import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Layout auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 h-screen">
      <div className="flex items-center flex-col justify-center">
        {children}
      </div>
      <div className="bg-[url(/bg-login.jpg)] bg-cover bg-no-repeat hidden md:block w-full h-full" />
    </div>
  );
}
